version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    ports:
      - '8000:8000'
    env_file: .env

  celery:
    build:
      context: .
      dockerfile: celery.dockerfile
    env_file: .env

  flower:
    image: mher/flower:0.9.7
    command: ["flower", "--broker", "${CELERY_BROKER_CON_STRING}"]
    ports:
      - '5555:5555'

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PASSWORD}'
    volumes:
      - mongo:/data/db

  mongo-ui:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_URL: '${MONGO_CONNECTION_STRING}'

  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - '15672:15672'

volumes:
  mongo:
  rabbitmq:
